name: Deploy Web (GitHub Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install Trunk
        run: |
          cargo install trunk

      - name: Build Web App (Trunk)
        working-directory: hc_curve_rs/hc_curve_web
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          trunk build --release --dist dist --public-url "/${REPO_NAME}/"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: hc_curve_rs/hc_curve_web/dist
          publish_branch: gh-pages
          force_orphan: true

